const translations = {
    ru: {
        title: "Свойства блока",
        baseType: "Тип блока, который будет использоваться как хитбокс, барьер универсальный",
        hat: "Игрок может надеть блок себе на голову через инвентарь.",
        solid: "Если отключено, то базовый тип не будет использоваться. Блок будет иметь хитбокс-сущность",
        offset: "Смещение хитбокса относительно центра блока",
        destroyTime: "Время разрушения блока в секундах",
        freePlace: "Если включено, блок можно разместить в любом месте, независимо от сетки блоков.",
        instrument: "Эффективный инструмент",
        seat: "Сможет ли игрок сесть на этот блок, нажав ПКМ?",
        seatPos: "Позиция, где будет сидеть игрок.<br> 0 0 0 - центр блока",
        seatRotate: "Будет ли модель вращаться, следуя за телом сидящего игрока?",
        sidePlace: "С каких сторон блока можно разместить этот блок?",
        modelBlock: "Какой предмет будет отображаться при размещении блока",
        modelItem: "Какой предмет будет отображаться в инвентаре игрока",
        modelColor: "Поддерживаются только <b>leather_armor</b> и <b>leather_horse_armor</b>",
        lore: "Можно разделить \\n для новых строк. Оставьте пустым, чтобы не было лора.",
        modelProperties: "Свойства модели установленного блока",
        modelOffset: "Смещение",
        modelRotation: "Поворот",
        modelScale: "Размер",
        isRotates: "Если эта функция включена, блок будет поворачиваться к игроку при размещении, например, как сундук.",
        rotate45: "Поворот похожий на головы",
        rotateFree: "Модель поворачивается точно на игрока",
        rotateFace: "Вращение зависит от стороны блока, на которой этот блок установлен. Аналогично вращению рамки или картины.",
        binding: "Сторона модели, которой она должна быть прикреплена к блоку. Blockface указывается в соответствии с BlockBench",
        blockOffset: "Заменяет смещение из раздела Model. Смещение относительно стороны блока, на которой этот блок размещен",
        inventory: "Открывает инвентарь на RMB",
        lines: "Количество строчек",
        maxStack: "Размер стака",
        maxStackTip: "Максимальный размер стака этого блока. Если используется предмет с максимальным стаком меньше указанного, это вызовет ошибку",
        addBlocks: "Полезно, если вы хотите сделать блок, состоящий из нескольких блоков. Например, диван длиной в три блока.<br><br>\n" +
            "id - Имя файла кастомного блока<br>\n" +
            "если блок по id не найден, он пропускается<br>\n" +
            "x y z - смещение в блоках относительно основного блока. 0 0 0 - ничего не сделает",
        recipe: "Разместите символы в ячейках так, как предметы должны быть размещены в верстаке. Не заполняйте пустые слоты.",
        ingredients: "Назначьте каждому символу spigot материал, например, stone, diamond, stick.\n" +
            "Или вы можете использовать теги minecraft, например, #minecraft:planks, #minecraft:logs, #minecraft:wooden_slabs",
        interactSound: "Воспроизводится, когда игрок садится на блок или открывает инвентарь блока.",
        dimension: "Измерение",
        minHeight: "Минимальная высота на которой сможет появится эта руда",
        maxHeight: "Максимальная высота на которой сможет появится эта руда",
        maxBlocks: "Максимальное количество блоков в одной жиле этой руды",
        maxVeins: "Максимальное количество жил на один чанк",
        copied: "Скопировано в буфер обмена!",
        copiedSub: "Вставьте этот текст в MeowFurniture/blocks/your_block.yml",
        selectExample: "Выберите Блок-Пример",
        exSeat: "Стул ступеньки",
        exOre: "Руда",
        exPainting: "Картина",
        exDrawer: "Ящик",
        exHangingDrawer: "Навесной ящик",
        exHat: "Шляпа",
        requireTool: "Нужен ли выбранный ранее инструмент для выпадения блока",
        effectiveMaterial: "Эффективный материал инструмента",
        effectiveMaterialText: "Минимальный материал инструмента нужный для выпадения блока",
        exFlower: "Цветок",
        exFlowerFree: "Цветок (Free place)",
        exTripleChair: "Тройной стул",
        exTripleChairPart: "triple_chair_part (Нужен для тройного стула)",
        hasCommands: "Команды, которые консоль выполнит, когда игрок нажмет на блок. Плейсхолдеры будут выполнены от имени игрока, который нажал на блок.<br> Используй %block_x%, %block_y%, %block_z% для получения координат блока",
        hasPlaceCommands: "Команды, которые консоль выполнит, когда игрок поставил блок. Плейсхолдеры будут выполнены от имени игрока, который поставил блок.<br> Используй %block_x%, %block_y%, %block_z% для получения координат блока",
        hasBreakCommands: "Команды, которые консоль выполнит, когда игрок сломал блок. Плейсхолдеры будут выполнены от имени игрока, который сломал блок.<br> Используй %block_x%, %block_y%, %block_z% для получения координат блока",
        overlay: "Прописывается путь до оверлея шляпы, например \"misc/pumpkinblur\" для оверлея тыквы!",
        emmmm: "",

        cancel: "Отмена"
    },
    en: {
        title: "Block properties",
        baseType: "The type of block that will be used as a hitbox, barrier universal",
        hat: "The player can put a block on his head through the inventory.",
        solid: "If disabled, the Base Type will not be used. The block will have a hitbox entity.",
        offset: "Offset of hitbox relative to block center",
        freePlace: "If enabled, the block can be placed anywhere, regardless of the block grid",
        destroyTime: "Block break time in seconds",
        instrument: "Effective instrument",
        seat: "Will the player be able to sit on this block by pressing RMB",
        seatPos: "The position where the player will sit.<br> 0 0 0 - center of the block",
        seatRotate: "Will the model rotate to follow the body of a seated player?",
        sidePlace: "On which sides of the block can this block be placed?",
        modelBlock: "What item will be displayed when the block is placed",
        modelItem: "What item will be displayed when the block is in inventory",
        modelColor: "Only <b>leather_armor</b> and <b>leather_horse_armor</b> are supported",
        lore: "Can be separated with \\n for new lines. Leave blank for no lore.",
        modelProperties: "Properties of the placed block model",
        modelOffset: "Offset",
        modelRotation: "Rotation",
        modelScale: "Scale",
        isRotates: "If enabled, the block will turn towards the player when placed, like a chest for example.",
        rotate45: "Rotation similar to heads.",
        rotateFree: "The model will turn exactly towards the player.",
        rotateFace: "The rotation depends on the side of the block on which this block is placed. Similar to the rotation of the frame or painting",
        binding: "The side of the model that it should be attached to the block. Blockface is specified according to BlockBench",
        blockOffset: "Replaces the offset from the Model section. Offsets relative to the side of the block on which this block is placed",
        inventory: "Opens inventory on RMB",
        lines: "Number of lines:",
        maxStack: "Max Stack:",
        maxStackTip: "The maximum stack size of this block. If an item with a maximum stack less than the specified one is used, it will cause an error",
        addBlocks: "Useful if you want to make a block consisting of several blocks. For example, a sofa three blocks long.<br><br>\n" +
            "                  id - Custom block file name<br>\n" +
            "                  if a block by id is not found, it is skipped<br>\n" +
            "                  x y z - offset in blocks, relative to the main block. 0 0 0 - will do nothing",
        recipe: "Place the symbols in the cells as the items should be placed in the crafting table. Do not fill empty slots.",
        ingredients: "Assign each symbol a spigot material, such as stone, diamond, stick.\n" +
            "Or you can use minecraft tags, such as #minecraft:planks, #minecraft:logs, #minecraft:wooden_slabs",
        interactSound: "Plays when the player sits on a block or opens the block's inventory.",
        dimension: "Dimension",
        minHeight: "Minimum height where this ore can spawn",
        maxHeight: "Maximum height where this ore can spawn",
        maxBlocks: "Maximum number of blocks in one vein of this ore",
        maxVeins: "Maximum number of veins per chunk",
        copied: "Copied to clipboard!",
        copiedSub: "Paste this text into MeowFurniture/blocks/your_block.yml",
        selectExample: "Select Example Block",
        exSeat: "Stairs Seat",
        exOre: "Ore",
        exPainting: "Painting",
        exDrawer: "Drawer",
        exHangingDrawer: "Hanging Drawer",
        exHat: "Hat",
        requireTool: "Whether the previously selected tool is required for the block to drop",
        effectiveMaterial: "Effective tool material",
        effectiveMaterialText: "The minimum tool material required for the block to drop",
        exFlower: "Flower",
        exFlowerFree: "Flower (Free place)",
        exTripleChair: "Triple Chair",
        exTripleChairPart: "triple_chair_part (Need for Triple Chair)",
        hasCommands: "Commands that the console will execute when the player clicks on the block. Placeholders will be executed as the player who clicked the block.<br> Use %block_x%, %block_y%, %block_z% to get the block's coordinates.",
        hasPlaceCommands: "Commands that the console will execute when the player places the block. Placeholders will be executed as the player who placed the block.<br> Use %block_x%, %block_y%, %block_z% to get the block's coordinates.",
        hasBreakCommands: "Commands that the console will execute when the player breaks the block. Placeholders will be executed as the player who broke the block.<br> Use %block_x%, %block_y%, %block_z% to get the block's coordinates.",
        overlay: "The path to the hat overlay is specified, for example \"misc/pumpkinblur\" for the pumpkin overlay!",
        cancel: "cancel"
    },
    uk: {
        title: "Властивості блоку",
        baseType: "Тип блоку, який буде використовуватися як хитбокс, універсальна перешкода",
        hat: "Гравець може одягнути блок собі на голову через інвентар.",
        solid: "Якщо вимкнено, базовий тип не буде використовуватися. Блок матиме хитбокс-сутність.",
        offset: "Зсув хитбоксу відносно центру блоку",
        destroyTime: "Час руйнування блоку в секундах",
        freePlace: "Якщо ввімкнено, блок можна розмістити будь-де, незалежно від сітки блоків.",
        instrument: "Ефективний інструмент",
        seat: "Чи зможе гравець сісти на цей блок, натиснувши ПКМ?",
        seatPos: "Позиція, де сидітиме гравець.<br> 0 0 0 - центр блоку",
        seatRotate: "Чи буде модель обертатися слідом за тілом гравця, який сидить?",
        sidePlace: "З яких боків блоку можна розмістити цей блок?",
        modelBlock: "Який предмет буде відображатися при розміщенні блоку",
        modelItem: "Який предмет буде відображатися в інвентарі гравця",
        modelColor: "Підтримуються лише <b>leather_armor</b> і <b>leather_horse_armor</b>",
        lore: "Можна розділити \\n для нових рядків. Залиште порожнім, щоб не було опису.",
        modelProperties: "Властивості моделі встановленого блоку",
        modelOffset: "Зсув",
        modelRotation: "Обертання",
        modelScale: "Масштаб",
        isRotates: "Якщо ця функція увімкнена, блок буде повертатися до гравця при розміщенні, наприклад, як скриня.",
        rotate45: "Обертання схоже на голови",
        rotateFree: "Модель точно повертається до гравця",
        rotateFace: "Обертання залежить від сторони блоку, на яку цей блок встановлено. Аналогічно обертанню рамки або картини.",
        binding: "Сторона моделі, якою вона має бути прикріплена до блоку. Blockface задається як у BlockBench",
        blockOffset: "Замінює зсув із розділу Model. Зсув відносно сторони блоку, на яку цей блок встановлений",
        inventory: "Відкриває інвентар на ПКМ",
        lines: "Кількість рядків",
        maxStack: "Розмір стака",
        maxStackTip: "Максимальний розмір стака цього блоку. Якщо використовується предмет із меншим стаком, виникне помилка",
        addBlocks: "Корисно, якщо ви хочете створити блок, що складається з кількох блоків. Наприклад, диван довжиною три блоки.<br><br>\n" +
            "id - Назва файлу користувацького блоку<br>\n" +
            "якщо блок із вказаним id не знайдено, він пропускається<br>\n" +
            "x y z - зсув у блоках відносно основного блоку. 0 0 0 - нічого не зробить",
        recipe: "Розмістіть символи в комірках так, як предмети мають бути у верстаку. Не заповнюйте порожні комірки.",
        ingredients: "Призначте кожному символу матеріал Spigot, наприклад stone, diamond, stick.\n" +
            "Або можна використовувати теги Minecraft, наприклад, #minecraft:planks, #minecraft:logs, #minecraft:wooden_slabs",
        interactSound: "Відтворюється, коли гравець сідає на блок або відкриває його інвентар.",
        dimension: "Вимір",
        minHeight: "Мінімальна висота, на якій може з'явитися ця руда",
        maxHeight: "Максимальна висота, на якій може з'явитися ця руда",
        maxBlocks: "Максимальна кількість блоків в одній жилі цієї руди",
        maxVeins: "Максимальна кількість жил на один чанк",
        copied: "Скопійовано до буфера обміну!",
        copiedSub: "Вставте цей текст у MeowFurniture/blocks/your_block.yml",
        selectExample: "Вибрати приклад блоку",
        exSeat: "Сидіння на сходах",
        exOre: "Руда",
        exPainting: "Картина",
        requireTool: "Чи потрібен раніше вибраний інструмент для випадіння блоку",
        effectiveMaterial: "Ефективний матеріал інструменту",
        effectiveMaterialText: "Мінімальний матеріал інструменту, потрібний для випадіння блоку",
        exFlower: "Квітка",
        exFlowerFree: "Квітка (Вільне розміщення)",
        exTripleChair: "Потрійний стілець",
        "exDrawer": "Шухляда",
        "exHangingDrawer": "Підвісна шухляда",
        "exHat": "Капелюх",
        exTripleChairPart: "triple_chair_part (Потрібно для потрійного стільця)",
        hasCommands: "Команди, які консоль виконає, коли гравець натисне на блок. Плейсхолдери будуть виконані від імені гравця, який натиснув на блок.<br> Використовуйте %block_x%, %block_y%, %block_z% для отримання координат блока.",
        hasPlaceCommands: "Команди, які консоль виконає, коли гравець поставить блок. Плейсхолдери будуть виконані від імені гравця, який поставив блок.<br> Використовуйте %block_x%, %block_y%, %block_z% для отримання координат блока.",
        hasBreakCommands: "Команди, які консоль виконає, коли гравець зламає блок. Плейсхолдери будуть виконані від імені гравця, який зламав блок.<br> Використовуйте %block_x%, %block_y%, %block_z% для отримання координат блока.",
        overlay: "Прописується шлях до оверлея капелюха, наприклад \"misc/pumpkinblur\" для оверлея гарбуза!",
        emmmm: "",
        cancel: "Скасувати"
    },
    es: {
        title: "Propiedades del bloque",
        baseType: "El tipo de bloque que se usará como caja de colisión, barrera universal",
        hat: "El jugador puede ponerse el bloque en la cabeza a través del inventario.",
        solid: "Si está desactivado, no se usará el tipo base. El bloque tendrá una entidad de colisión.",
        offset: "Desplazamiento del hitbox relativo al centro del bloque",
        destroyTime: "Tiempo de rotura del bloque en segundos",
        freePlace: "Si está activado, el bloque se puede colocar en cualquier parte, independientemente de la cuadrícula.",
        instrument: "Herramienta eficaz",
        seat: "¿Puede el jugador sentarse en este bloque al hacer clic derecho?",
        seatPos: "Posición donde se sentará el jugador.<br> 0 0 0 - centro del bloque",
        seatRotate: "¿La modelo girará siguiendo el cuerpo del jugador sentado?",
        sidePlace: "¿Desde qué lados se puede colocar este bloque?",
        modelBlock: "Qué objeto se mostrará al colocar el bloque",
        modelItem: "Qué objeto se mostrará en el inventario",
        modelColor: "Solo se admiten <b>leather_armor</b> y <b>leather_horse_armor</b>",
        lore: "Se puede dividir con \\n para nuevas líneas. Déjelo en blanco para que no tenga descripción.",
        modelProperties: "Propiedades del modelo del bloque colocado",
        modelOffset: "Desplazamiento",
        modelRotation: "Rotación",
        modelScale: "Escala",
        isRotates: "Si está activado, el bloque se girará hacia el jugador al colocarlo, como un cofre.",
        rotate45: "Rotación similar a las cabezas",
        rotateFree: "El modelo se gira exactamente hacia el jugador",
        rotateFace: "La rotación depende del lado del bloque donde se coloque. Similar a un marco o un cuadro.",
        binding: "Lado del modelo que debe estar unido al bloque. El Blockface se especifica según BlockBench",
        blockOffset: "Reemplaza el desplazamiento de la sección Model. Desplazamiento relativo al lado del bloque donde se coloca",
        inventory: "Abre inventario con clic derecho",
        lines: "Número de líneas",
        maxStack: "Tamaño del stack",
        maxStackTip: "El tamaño máximo del stack de este bloque. Si se usa un objeto con un stack menor, provocará un error",
        addBlocks: "Útil si quieres hacer un bloque compuesto por varios bloques. Por ejemplo, un sofá de tres bloques de largo.<br><br>\n" +
            "id - Nombre del archivo del bloque personalizado<br>\n" +
            "si no se encuentra un bloque con ese id, se omite<br>\n" +
            "x y z - desplazamiento en bloques respecto al bloque principal. 0 0 0 - no hace nada",
        recipe: "Coloca los símbolos en las celdas como deben ir en la mesa de trabajo. No rellenes los huecos vacíos.",
        ingredients: "Asigna a cada símbolo un material Spigot, como stone, diamond, stick.\n" +
            "O puedes usar etiquetas de Minecraft, como #minecraft:planks, #minecraft:logs, #minecraft:wooden_slabs",
        interactSound: "Se reproduce cuando el jugador se sienta en el bloque o abre su inventario.",
        dimension: "Dimensión",
        minHeight: "Altura mínima donde puede aparecer este mineral",
        maxHeight: "Altura máxima donde puede aparecer este mineral",
        maxBlocks: "Cantidad máxima de bloques en una veta de este mineral",
        maxVeins: "Cantidad máxima de vetas por chunk",
        copied: "¡Copiado al portapapeles!",
        copiedSub: "Pega este texto en MeowFurniture/blocks/your_block.yml",
        selectExample: "Seleccionar bloque de ejemplo",
        exSeat: "Asiento de escaleras",
        exOre: "Mena",
        exPainting: "Cuadro",
        "exDrawer": "Cajón",
        "exHangingDrawer": "Cajón colgante",
        "exHat": "Sombrero",
        requireTool: "Si se requiere la herramienta seleccionada previamente para que caiga el bloque",
        effectiveMaterial: "Material efectivo de la herramienta",
        effectiveMaterialText: "El material mínimo de herramienta requerido para que caiga el bloque",
        exFlower: "Flor",
        exFlowerFree: "Flor (Colocación libre)",
        exTripleChair: "Silla triple",
        exTripleChairPart: "triple_chair_part (Necesario para la silla triple)",
        hasCommands: "Comandos que la consola ejecutará cuando el jugador haga clic en el bloque. Los marcadores de posición se ejecutarán como el jugador que hizo clic en el bloque.<br> Usa %block_x%, %block_y%, %block_z% para obtener las coordenadas del bloque.",
        hasPlaceCommands: "Comandos que la consola ejecutará cuando el jugador coloque el bloque. Los marcadores de posición se ejecutarán como el jugador que colocó el bloque.<br> Usa %block_x%, %block_y%, %block_z% para obtener las coordenadas del bloque.",
        hasBreakCommands: "Comandos que la consola ejecutará cuando el jugador rompa el bloque. Los marcadores de posición se ejecutarán como el jugador que rompió el bloque.<br> Usa %block_x%, %block_y%, %block_z% para obtener las coordenadas del bloque.",
        overlay: "Se especifica la ruta a la superposición del sombrero, por ejemplo, \"misc/pumpkinblur\" para la superposición de calabaza",
        emmmm: "",
        cancel: "Cancelar"
    },
    de: {
        title: "Blockeigenschaften",
        baseType: "Der Blocktyp, der als Hitbox verwendet wird, universelle Barriere",
        hat: "Der Spieler kann den Block über das Inventar auf den Kopf setzen.",
        solid: "Wenn deaktiviert, wird der Basistyp nicht verwendet. Der Block hat eine Hitbox-Entität.",
        offset: "Versatz der Hitbox relativ zur Blockmitte",
        destroyTime: "Zeit zum Zerstören des Blocks in Sekunden",
        freePlace: "Wenn aktiviert, kann der Block überall platziert werden, unabhängig vom Blockraster.",
        instrument: "Effektives Werkzeug",
        seat: "Kann der Spieler durch Rechtsklick auf diesem Block sitzen?",
        seatPos: "Position, an der der Spieler sitzen wird.<br> 0 0 0 - Zentrum des Blocks",
        seatRotate: "Soll sich das Modell zur Körperausrichtung des sitzenden Spielers drehen?",
        sidePlace: "Auf welchen Seiten des Blocks kann dieser Block platziert werden?",
        modelBlock: "Welcher Gegenstand wird angezeigt, wenn der Block platziert ist",
        modelItem: "Welcher Gegenstand wird im Inventar angezeigt",
        modelColor: "Nur <b>leather_armor</b> und <b>leather_horse_armor</b> werden unterstützt",
        lore: "Kann mit \\n für neue Zeilen getrennt werden. Leer lassen für keine Beschreibung.",
        modelProperties: "Eigenschaften des platzierten Blockmodells",
        modelOffset: "Versatz",
        modelRotation: "Rotation",
        modelScale: "Größe",
        isRotates: "Wenn aktiviert, wird der Block beim Platzieren dem Spieler zugewandt, wie z.B. eine Truhe.",
        rotate45: "Rotation ähnlich wie bei Köpfen.",
        rotateFree: "Das Modell dreht sich exakt zum Spieler.",
        rotateFace: "Die Rotation hängt von der Blockseite ab, auf der dieser Block platziert wird. Ähnlich wie bei Rahmen oder Gemälden.",
        binding: "Die Seite des Modells, die am Block befestigt werden soll. Die Blockseite wird gemäß BlockBench angegeben.",
        blockOffset: "Ersetzt den Versatz aus dem Modellabschnitt. Versatz relativ zur Seite des Blocks, auf der dieser Block platziert ist.",
        inventory: "Öffnet Inventar mit Rechtsklick",
        lines: "Anzahl der Zeilen",
        maxStack: "Maximaler Stapel",
        maxStackTip: "Maximale Stapelgröße dieses Blocks. Wenn ein Gegenstand mit niedrigerer Stapelgröße verwendet wird, tritt ein Fehler auf.",
        addBlocks: "Nützlich, wenn du einen Block erstellen möchtest, der aus mehreren Blöcken besteht. Zum Beispiel ein Sofa mit drei Blöcken Länge.<br><br>\n" +
            "id - Name der benutzerdefinierten Blockdatei<br>\n" +
            "wenn der Block mit der ID nicht gefunden wird, wird er übersprungen<br>\n" +
            "x y z - Versatz in Blöcken relativ zum Hauptblock. 0 0 0 - bewirkt nichts",
        recipe: "Platziere die Symbole in den Feldern so, wie die Gegenstände im Crafting-Tisch angeordnet sein sollen. Leere Felder nicht ausfüllen.",
        ingredients: "Weise jedem Symbol ein Spigot-Material zu, z.B. stone, diamond, stick.\n" +
            "Oder verwende Minecraft-Tags wie #minecraft:planks, #minecraft:logs, #minecraft:wooden_slabs",
        interactSound: "Wird abgespielt, wenn der Spieler auf dem Block sitzt oder dessen Inventar öffnet.",
        dimension: "Dimension",
        minHeight: "Minimale Höhe, auf der dieses Erz erscheinen kann",
        maxHeight: "Maximale Höhe, auf der dieses Erz erscheinen kann",
        maxBlocks: "Maximale Anzahl an Blöcken in einem Erzvorkommen",
        maxVeins: "Maximale Anzahl an Vorkommen pro Chunk",
        copied: "In die Zwischenablage kopiert!",
        copiedSub: "Füge diesen Text in MeowFurniture/blocks/your_block.yml ein",
        selectExample: "Beispielformat auswählen",
        exSeat: "Treppensitz",
        exOre: "Erz",
        exPainting: "Gemälde",
        "exDrawer": "Schublade",
        "exHangingDrawer": "Hängende Schublade",
        "exHat": "Hut",
        requireTool: "Ob das zuvor ausgewählte Werkzeug zum Droppen des Blocks benötigt wird",
        effectiveMaterial: "Effektives Werkzeugmaterial",
        effectiveMaterialText: "Das minimale Werkzeugmaterial, das zum Droppen des Blocks benötigt wird",
        exFlower: "Blume",
        exFlowerFree: "Blume (Freie Platzierung)",
        exTripleChair: "Dreifachstuhl",
        exTripleChairPart: "triple_chair_part (Erforderlich für den Dreifachstuhl)",
        hasCommands: "Befehle, die die Konsole ausführt, wenn der Spieler auf den Block klickt. Platzhalter werden im Namen des Spielers ausgeführt, der auf den Block geklickt hat.<br> Verwende %block_x%, %block_y%, %block_z%, um die Koordinaten des Blocks zu erhalten.",
        hasPlaceCommands: "Befehle, die die Konsole ausführt, wenn der Spieler den Block platziert. Platzhalter werden im Namen des Spielers ausgeführt, der den Block platziert hat.<br> Verwende %block_x%, %block_y%, %block_z%, um die Koordinaten des Blocks zu erhalten.",
        hasBreakCommands: "Befehle, die die Konsole ausführt, wenn der Spieler den Block zerstört. Platzhalter werden im Namen des Spielers ausgeführt, der den Block zerstört hat.<br> Verwende %block_x%, %block_y%, %block_z%, um die Koordinaten des Blocks zu erhalten.",
        overlay: "Der Pfad zum Hut-Overlay ist angegeben, zum Beispiel \"misc/pumpkinblur\" für das Kürbis-Overlay!",
        cancel: "Abbrechen"
    },
    be: {
        title: "Уласцівасці блока",
        baseType: "Тып блока, які выкарыстоўваецца як хітбокс, універсальная перашкода",
        hat: "Гулец можа надзець блок на галаву праз інвентар.",
        solid: "Калі адключана, базавы тып не выкарыстоўваецца. Блок будзе мець хітбокс-сутнасць.",
        offset: "Змяшчэнне хітбокса адносна цэнтра блока",
        destroyTime: "Час разбурэння блока ў секундах",
        freePlace: "Калі ўключана, блок можна ставіць у любым месцы, незалежна ад сеткі блокаў.",
        instrument: "Эфектыўны інструмент",
        seat: "Ці можа гулец сесці на гэты блок, націснуўшы ПКМ?",
        seatPos: "Пазіцыя, дзе будзе сядзець гулец.<br> 0 0 0 — цэнтр блока",
        seatRotate: "Ці будзе мадэль паварочвацца за целам седзячага гульца?",
        sidePlace: "З якіх бакоў можна размяшчаць гэты блок?",
        modelBlock: "Які прадмет будзе адлюстроўвацца пры ўстаноўцы блока",
        modelItem: "Які прадмет будзе адлюстроўвацца ў інвентары",
        modelColor: "Падтрымліваюцца толькі <b>leather_armor</b> і <b>leather_horse_armor</b>",
        lore: "Можна раздзяліць \\n для новых радкоў. Пакіньце пустым, калі не патрэбен тэкст.",
        modelProperties: "Уласцівасці мадэлі ўсталяванага блока",
        modelOffset: "Змяшчэнне",
        modelRotation: "Паварот",
        modelScale: "Маштаб",
        isRotates: "Калі ўключана, блок будзе паварочвацца да гульца пры ўсталёўцы, як, напрыклад, куфар.",
        rotate45: "Паварот падобны да галоў.",
        rotateFree: "Мадэль дакладна паварочваецца да гульца.",
        rotateFace: "Паварот залежыць ад боку блока, на які ўсталяваны блок. Падобна на рамкі або карціны.",
        binding: "Бок мадэлі, якім яна павінна мацавацца да блока. Blockface паказваецца як у BlockBench.",
        blockOffset: "Замяняе змяшчэнне з раздзела мадэлі. Змяшчэнне адносна боку блока.",
        inventory: "Адкрывае інвентар па ПКМ",
        lines: "Колькасць радкоў",
        maxStack: "Памер стэка",
        maxStackTip: "Максімальны памер стэка. Калі выкарыстоўваецца прадмет з меншым максімумам — будзе памылка.",
        addBlocks: "Карысна для стварэння блока з некалькіх частак. Напрыклад, канапа з трох блокаў.<br><br>\n" +
            "id — імя файла карыстацкага блока<br>\n" +
            "калі блок не знойдзены — прапускаецца<br>\n" +
            "x y z — змяшчэнне адносна асноўнага блока. 0 0 0 — нічога не робіць",
        recipe: "Размясціце сімвалы так, як прадметы павінны размяшчацца ў варштаку. Не запаўняйце пустыя ячэйкі.",
        ingredients: "Прызначце кожнаму сімвалу матэрыял Spigot, напрыклад stone, diamond, stick.\n" +
            "Або выкарыстоўвайце тэгі Minecraft, напрыклад #minecraft:planks, #minecraft:logs, #minecraft:wooden_slabs",
        interactSound: "Гучыць, калі гулец садзіцца на блок або адкрывае інвентар блока.",
        dimension: "Вымярэнне",
        minHeight: "Мінімальная вышыня, на якой можа з'явіцца гэтая руда",
        maxHeight: "Максімальная вышыня, на якой можа з'явіцца гэтая руда",
        maxBlocks: "Максімальная колькасць блокаў у адной жиле гэтай руды",
        maxVeins: "Максімальная колькасць жил на адзін чанк",
        copied: "Скапіявана ў буфер абмену!",
        copiedSub: "Устаўце гэты тэкст у MeowFurniture/blocks/your_block.yml",
        selectExample: "Выбраць прыклад блока",
        exSeat: "Сядзенне на прыступках",
        exOre: "Руда",
        exPainting: "Карціна",
        "exDrawer": "Шуфлядка",
        "exHangingDrawer": "Падвесная шуфлядка",
        "exHat": "Капялюш",
        requireTool: "Ці патрабуецца раней выбраны інструмент для выпадзення блока",
        effectiveMaterial: "Эфектыўны матэрыял інструмента",
        effectiveMaterialText: "Мінімальны матэрыял інструмента, неабходны для выпадзення блока",
        exFlower: "Кветка",
        exFlowerFree: "Кветка (Вольнае размяшчэнне)",
        exTripleChair: "Патройны крэсла",
        exTripleChairPart: "triple_chair_part (Неабходна для патройнага крэсла)",
        hasCommands: "Каманды, якія кансоль выканае, калі гулец націсне на блок. Плэйсхолдары будуць выкананы ад імя гульца, які націснуў на блок.<br> Выкарыстоўвайце %block_x%, %block_y%, %block_z% для атрымання каардынат блока.",
        hasPlaceCommands: "Каманды, якія кансоль выканае, калі гулец паставіць блок. Плэйсхолдары будуць выкананы ад імя гульца, які паставіў блок.<br> Выкарыстоўвайце %block_x%, %block_y%, %block_z% для атрымання каардынат блока.",
        hasBreakCommands: "Каманды, якія кансоль выканае, калі гулец зломіць блок. Плэйсхолдары будуць выкананы ад імя гульца, які зламаў блок.<br> Выкарыстоўвайце %block_x%, %block_y%, %block_z% для атрымання каардынат блока.",
        overlay: "Прапісваецца шлях да оверлея капялюшы, напрыклад \"misc/pumpkinblur\" для оверлея гарбуза!",
        cancel: "Адмена"
    }


};

function applyTranslations(lang) {
    document.querySelectorAll("[data-i18n]").forEach(el => {
        const key = el.getAttribute("data-i18n");
        el.innerHTML = translations[lang][key] || key;
    });
}

